# Generated by Django 5.1.7 on 2025-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_verified',
        ),
        migrations.AddField(
            model_name='application',
            name='payment_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
